#!/usr/bin/env php
<?php


$pathToAutoload = realpath(__DIR__ . '/../src/vendor/autoload.php');

$errorMessage = "
Cannot find composer dependencies.
Run below command and try again;\n
$ cd %s
$ composer install -d src
";

if (!$pathToAutoload) {
    echo sprintf($errorMessage, realpath(__DIR__ . '/../'));
    exit(1);
}

use OrangeHRM\Framework\Console\Console;
use OrangeHRM\Framework\Http\Session\MemorySessionStorage;
use OrangeHRM\Framework\Http\Session\Session;
use OrangeHRM\Framework\ServiceContainer;
use OrangeHRM\Framework\Services;
use OrangeHRM\Installer\Command\InstallerCountryListCommand;
use OrangeHRM\Installer\Command\InstallOnExistingDatabaseCommand;
use OrangeHRM\Installer\Command\InstallOnNewDatabaseCommand;
use OrangeHRM\Installer\Command\UpgradeCommand;
use OrangeHRM\Installer\Framework\HttpKernel;

set_time_limit(0);

require_once $pathToAutoload;

$env = 'prod';
$debug = 'prod' !== $env;

$console = new Console();
new HttpKernel($env, $debug); // initializing kernel
$sessionStorage = new MemorySessionStorage();
ServiceContainer::getContainer()->set(Services::SESSION_STORAGE, $sessionStorage);
$session = new Session($sessionStorage);
$session->start();
ServiceContainer::getContainer()->set(Services::SESSION, $session);

$console->add(new InstallOnNewDatabaseCommand());
$console->add(new InstallOnExistingDatabaseCommand());
$console->add(new UpgradeCommand());
$console->add(new InstallerCountryListCommand());

$console->setName('OrangeHRM Command Line Installer');
$console->setVersion('1.0.0');
$console->run();
